// Mocks generated by Mockito 5.4.6 from annotations
// in stoyco_shared/test/moengage/moengage_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:moengage_flutter/moengage_flutter.dart' as _i3;
import 'package:stoyco_shared/moengage/moengage_platform.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [MoEngagePlatform].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoEngagePlatform extends _i1.Mock implements _i2.MoEngagePlatform {
  MockMoEngagePlatform() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void initialize({
    required String? appId,
    String? pushToken,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {
            #appId: appId,
            #pushToken: pushToken,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void identifyUser(String? uniqueId) => super.noSuchMethod(
        Invocation.method(
          #identifyUser,
          [uniqueId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trackCustomEvent(
    String? eventName,
    Map<String, Object>? eventAttributes,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #trackCustomEvent,
          [
            eventName,
            eventAttributes,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setUserAttribute(
    String? attributeName,
    dynamic attributeValue,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setUserAttribute,
          [
            attributeName,
            attributeValue,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logout() => super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showInAppMessage() => super.noSuchMethod(
        Invocation.method(
          #showInAppMessage,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showNudge() => super.noSuchMethod(
        Invocation.method(
          #showNudge,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setUserName(String? userName) => super.noSuchMethod(
        Invocation.method(
          #setUserName,
          [userName],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setUserEmail(String? email) => super.noSuchMethod(
        Invocation.method(
          #setUserEmail,
          [email],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setGender(_i3.MoEGender? gender) => super.noSuchMethod(
        Invocation.method(
          #setGender,
          [gender],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setPhoneNumber(String? phoneNumber) => super.noSuchMethod(
        Invocation.method(
          #setPhoneNumber,
          [phoneNumber],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLastName(String? lastName) => super.noSuchMethod(
        Invocation.method(
          #setLastName,
          [lastName],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setFirstName(String? firstName) => super.noSuchMethod(
        Invocation.method(
          #setFirstName,
          [firstName],
        ),
        returnValueForMissingStub: null,
      );
}
