// Mocks generated by Mockito 5.4.6 from annotations
// in stoyco_shared/test/activity/activity_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:either_dart/either.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:stoyco_shared/activity/activity_data_source.dart' as _i15;
import 'package:stoyco_shared/activity/activity_repository.dart' as _i3;
import 'package:stoyco_shared/activity/models/activity_summary_model.dart'
    as _i13;
import 'package:stoyco_shared/activity/models/message_model.dart' as _i11;
import 'package:stoyco_shared/activity/models/message_stats_model.dart' as _i12;
import 'package:stoyco_shared/activity/models/notification_stats_model.dart'
    as _i10;
import 'package:stoyco_shared/activity/models/user_unified_stats_model.dart'
    as _i14;
import 'package:stoyco_shared/envs/envs.dart' as _i16;
import 'package:stoyco_shared/errors/error_handling/failure/failure.dart'
    as _i6;
import 'package:stoyco_shared/models/page_result/page_result.dart' as _i7;
import 'package:stoyco_shared/notification/model/notification_model.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ActivityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityRepository extends _i1.Mock
    implements _i3.ActivityRepository {
  MockActivityRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.PageResult<_i8.NotificationModel>>>
      getNotifications({
    int? page = 1,
    int? limit = 20,
    int? type,
    bool? unreadOnly,
    bool? expiredOnly,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getNotifications,
              [],
              {
                #page: page,
                #limit: limit,
                #type: type,
                #unreadOnly: unreadOnly,
                #expiredOnly: expiredOnly,
              },
            ),
            returnValue: _i4.Future<
                _i5.Either<
                    _i6.Failure,
                    _i7
                    .PageResult<_i8.NotificationModel>>>.value(_i9.dummyValue<
                _i5.Either<_i6.Failure, _i7.PageResult<_i8.NotificationModel>>>(
              this,
              Invocation.method(
                #getNotifications,
                [],
                {
                  #page: page,
                  #limit: limit,
                  #type: type,
                  #unreadOnly: unreadOnly,
                  #expiredOnly: expiredOnly,
                },
              ),
            )),
          ) as _i4.Future<
              _i5.Either<_i6.Failure, _i7.PageResult<_i8.NotificationModel>>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.PageResult<_i8.NotificationModel>>>
      searchNotifications(
    String? q, {
    int? page = 1,
    int? limit = 20,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #searchNotifications,
              [q],
              {
                #page: page,
                #limit: limit,
              },
            ),
            returnValue: _i4.Future<
                _i5.Either<
                    _i6.Failure,
                    _i7
                    .PageResult<_i8.NotificationModel>>>.value(_i9.dummyValue<
                _i5.Either<_i6.Failure, _i7.PageResult<_i8.NotificationModel>>>(
              this,
              Invocation.method(
                #searchNotifications,
                [q],
                {
                  #page: page,
                  #limit: limit,
                },
              ),
            )),
          ) as _i4.Future<
              _i5.Either<_i6.Failure, _i7.PageResult<_i8.NotificationModel>>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, bool>> markNotificationViewed(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markNotificationViewed,
          [id],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, bool>>.value(
            _i9.dummyValue<_i5.Either<_i6.Failure, bool>>(
          this,
          Invocation.method(
            #markNotificationViewed,
            [id],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, bool>> deleteNotification(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteNotification,
          [id],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, bool>>.value(
            _i9.dummyValue<_i5.Either<_i6.Failure, bool>>(
          this,
          Invocation.method(
            #deleteNotification,
            [id],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<
      _i5
      .Either<_i6.Failure, _i10.NotificationStatsModel>> getNotificationStats({
    bool? expiredOnly,
    bool? unreadOnly,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotificationStats,
          [],
          {
            #expiredOnly: expiredOnly,
            #unreadOnly: unreadOnly,
          },
        ),
        returnValue: _i4
            .Future<_i5.Either<_i6.Failure, _i10.NotificationStatsModel>>.value(
            _i9.dummyValue<
                _i5.Either<_i6.Failure, _i10.NotificationStatsModel>>(
          this,
          Invocation.method(
            #getNotificationStats,
            [],
            {
              #expiredOnly: expiredOnly,
              #unreadOnly: unreadOnly,
            },
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, _i10.NotificationStatsModel>>);

  @override
  _i4.Future<
      _i5.Either<_i6.Failure, _i7.PageResult<_i11.MessageModel>>> getMessages({
    int? page = 1,
    int? limit = 20,
    String? category,
    bool? unreadOnly,
    int? ageDays,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [],
          {
            #page: page,
            #limit: limit,
            #category: category,
            #unreadOnly: unreadOnly,
            #ageDays: ageDays,
          },
        ),
        returnValue: _i4.Future<
                _i5
                .Either<_i6.Failure, _i7.PageResult<_i11.MessageModel>>>.value(
            _i9.dummyValue<
                _i5.Either<_i6.Failure, _i7.PageResult<_i11.MessageModel>>>(
          this,
          Invocation.method(
            #getMessages,
            [],
            {
              #page: page,
              #limit: limit,
              #category: category,
              #unreadOnly: unreadOnly,
              #ageDays: ageDays,
            },
          ),
        )),
      ) as _i4
          .Future<_i5.Either<_i6.Failure, _i7.PageResult<_i11.MessageModel>>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.PageResult<_i11.MessageModel>>>
      searchMessages(
    String? q, {
    int? page = 1,
    int? limit = 20,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #searchMessages,
              [q],
              {
                #page: page,
                #limit: limit,
              },
            ),
            returnValue: _i4.Future<
                _i5.Either<_i6.Failure,
                    _i7.PageResult<_i11.MessageModel>>>.value(_i9.dummyValue<
                _i5.Either<_i6.Failure, _i7.PageResult<_i11.MessageModel>>>(
              this,
              Invocation.method(
                #searchMessages,
                [q],
                {
                  #page: page,
                  #limit: limit,
                },
              ),
            )),
          ) as _i4.Future<
              _i5.Either<_i6.Failure, _i7.PageResult<_i11.MessageModel>>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, bool>> markMessageViewed(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMessageViewed,
          [id],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, bool>>.value(
            _i9.dummyValue<_i5.Either<_i6.Failure, bool>>(
          this,
          Invocation.method(
            #markMessageViewed,
            [id],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, bool>> deleteMessage(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMessage,
          [id],
        ),
        returnValue: _i4.Future<_i5.Either<_i6.Failure, bool>>.value(
            _i9.dummyValue<_i5.Either<_i6.Failure, bool>>(
          this,
          Invocation.method(
            #deleteMessage,
            [id],
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, bool>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i12.MessageStatsModel>> getMessageStats({
    int? ageDays,
    bool? unreadOnly,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessageStats,
          [],
          {
            #ageDays: ageDays,
            #unreadOnly: unreadOnly,
          },
        ),
        returnValue:
            _i4.Future<_i5.Either<_i6.Failure, _i12.MessageStatsModel>>.value(
                _i9.dummyValue<_i5.Either<_i6.Failure, _i12.MessageStatsModel>>(
          this,
          Invocation.method(
            #getMessageStats,
            [],
            {
              #ageDays: ageDays,
              #unreadOnly: unreadOnly,
            },
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, _i12.MessageStatsModel>>);

  @override
  _i4.Future<
      _i5.Either<_i6.Failure, _i13.ActivitySummaryModel>> getActivitySummary({
    bool? unreadOnly,
    bool? expiredOnly,
    int? ageDays,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivitySummary,
          [],
          {
            #unreadOnly: unreadOnly,
            #expiredOnly: expiredOnly,
            #ageDays: ageDays,
          },
        ),
        returnValue: _i4
            .Future<_i5.Either<_i6.Failure, _i13.ActivitySummaryModel>>.value(
            _i9.dummyValue<_i5.Either<_i6.Failure, _i13.ActivitySummaryModel>>(
          this,
          Invocation.method(
            #getActivitySummary,
            [],
            {
              #unreadOnly: unreadOnly,
              #expiredOnly: expiredOnly,
              #ageDays: ageDays,
            },
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, _i13.ActivitySummaryModel>>);

  @override
  _i4.Future<
      _i5.Either<_i6.Failure, _i14.UserUnifiedStatsModel>> getUserUnifiedStats({
    bool? unreadOnly,
    bool? expiredOnly,
    int? ageDays,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserUnifiedStats,
          [],
          {
            #unreadOnly: unreadOnly,
            #expiredOnly: expiredOnly,
            #ageDays: ageDays,
          },
        ),
        returnValue: _i4
            .Future<_i5.Either<_i6.Failure, _i14.UserUnifiedStatsModel>>.value(
            _i9.dummyValue<_i5.Either<_i6.Failure, _i14.UserUnifiedStatsModel>>(
          this,
          Invocation.method(
            #getUserUnifiedStats,
            [],
            {
              #unreadOnly: unreadOnly,
              #expiredOnly: expiredOnly,
              #ageDays: ageDays,
            },
          ),
        )),
      ) as _i4.Future<_i5.Either<_i6.Failure, _i14.UserUnifiedStatsModel>>);
}

/// A class which mocks [ActivityDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityDataSource extends _i1.Mock
    implements _i15.ActivityDataSource {
  MockActivityDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.StoycoEnvironment get environment => (super.noSuchMethod(
        Invocation.getter(#environment),
        returnValue: _i16.StoycoEnvironment.development,
      ) as _i16.StoycoEnvironment);

  @override
  String get userToken => (super.noSuchMethod(
        Invocation.getter(#userToken),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#userToken),
        ),
      ) as String);

  @override
  set userToken(String? value) => super.noSuchMethod(
        Invocation.setter(
          #userToken,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateUserToken(String? newUserToken) => super.noSuchMethod(
        Invocation.method(
          #updateUserToken,
          [newUserToken],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i2.Response<dynamic>> getNotifications({
    int? page = 1,
    int? limit = 20,
    int? type,
    bool? unreadOnly,
    bool? expiredOnly,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotifications,
          [],
          {
            #page: page,
            #limit: limit,
            #type: type,
            #unreadOnly: unreadOnly,
            #expiredOnly: expiredOnly,
          },
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #getNotifications,
            [],
            {
              #page: page,
              #limit: limit,
              #type: type,
              #unreadOnly: unreadOnly,
              #expiredOnly: expiredOnly,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> searchNotifications({
    required String? q,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchNotifications,
          [],
          {
            #q: q,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #searchNotifications,
            [],
            {
              #q: q,
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> markNotificationViewed(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markNotificationViewed,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #markNotificationViewed,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> deleteNotification(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteNotification,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteNotification,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> getNotificationStats({
    bool? expiredOnly,
    bool? unreadOnly,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotificationStats,
          [],
          {
            #expiredOnly: expiredOnly,
            #unreadOnly: unreadOnly,
          },
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #getNotificationStats,
            [],
            {
              #expiredOnly: expiredOnly,
              #unreadOnly: unreadOnly,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> getMessages({
    int? page = 1,
    int? limit = 20,
    String? category,
    bool? unreadOnly,
    int? ageDays,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [],
          {
            #page: page,
            #limit: limit,
            #category: category,
            #unreadOnly: unreadOnly,
            #ageDays: ageDays,
          },
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #getMessages,
            [],
            {
              #page: page,
              #limit: limit,
              #category: category,
              #unreadOnly: unreadOnly,
              #ageDays: ageDays,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> searchMessages({
    required String? q,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMessages,
          [],
          {
            #q: q,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #searchMessages,
            [],
            {
              #q: q,
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> markMessageViewed(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMessageViewed,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #markMessageViewed,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> deleteMessage(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMessage,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteMessage,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> getMessageStats({
    int? ageDays,
    bool? unreadOnly,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessageStats,
          [],
          {
            #ageDays: ageDays,
            #unreadOnly: unreadOnly,
          },
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #getMessageStats,
            [],
            {
              #ageDays: ageDays,
              #unreadOnly: unreadOnly,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> getActivitySummary({
    bool? unreadOnly,
    bool? expiredOnly,
    int? ageDays,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivitySummary,
          [],
          {
            #unreadOnly: unreadOnly,
            #expiredOnly: expiredOnly,
            #ageDays: ageDays,
          },
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #getActivitySummary,
            [],
            {
              #unreadOnly: unreadOnly,
              #expiredOnly: expiredOnly,
              #ageDays: ageDays,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> getUserUnifiedStats({
    bool? unreadOnly,
    bool? expiredOnly,
    int? ageDays,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserUnifiedStats,
          [],
          {
            #unreadOnly: unreadOnly,
            #expiredOnly: expiredOnly,
            #ageDays: ageDays,
          },
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #getUserUnifiedStats,
            [],
            {
              #unreadOnly: unreadOnly,
              #expiredOnly: expiredOnly,
              #ageDays: ageDays,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);
}
