// Mocks generated by Mockito 5.4.6 from annotations
// in stoyco_shared/test/activity/activity_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:stoyco_shared/activity/activity_data_source.dart' as _i3;
import 'package:stoyco_shared/envs/envs.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ActivityDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityDataSource extends _i1.Mock
    implements _i3.ActivityDataSource {
  MockActivityDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.StoycoEnvironment get environment => (super.noSuchMethod(
        Invocation.getter(#environment),
        returnValue: _i4.StoycoEnvironment.development,
      ) as _i4.StoycoEnvironment);

  @override
  String get userToken => (super.noSuchMethod(
        Invocation.getter(#userToken),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#userToken),
        ),
      ) as String);

  @override
  set userToken(String? _userToken) => super.noSuchMethod(
        Invocation.setter(
          #userToken,
          _userToken,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateUserToken(String? newUserToken) => super.noSuchMethod(
        Invocation.method(
          #updateUserToken,
          [newUserToken],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i2.Response<dynamic>> getNotifications({
    int? page = 1,
    int? limit = 20,
    int? type,
    bool? unreadOnly,
    bool? expiredOnly,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotifications,
          [],
          {
            #page: page,
            #limit: limit,
            #type: type,
            #unreadOnly: unreadOnly,
            #expiredOnly: expiredOnly,
          },
        ),
        returnValue:
            _i6.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #getNotifications,
            [],
            {
              #page: page,
              #limit: limit,
              #type: type,
              #unreadOnly: unreadOnly,
              #expiredOnly: expiredOnly,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> searchNotifications({
    required String? q,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchNotifications,
          [],
          {
            #q: q,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i6.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #searchNotifications,
            [],
            {
              #q: q,
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> markNotificationViewed(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markNotificationViewed,
          [id],
        ),
        returnValue:
            _i6.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #markNotificationViewed,
            [id],
          ),
        )),
      ) as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> deleteNotification(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteNotification,
          [id],
        ),
        returnValue:
            _i6.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteNotification,
            [id],
          ),
        )),
      ) as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getNotificationStats({
    bool? expiredOnly,
    bool? unreadOnly,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotificationStats,
          [],
          {
            #expiredOnly: expiredOnly,
            #unreadOnly: unreadOnly,
          },
        ),
        returnValue:
            _i6.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #getNotificationStats,
            [],
            {
              #expiredOnly: expiredOnly,
              #unreadOnly: unreadOnly,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getMessages({
    int? page = 1,
    int? limit = 20,
    String? category,
    bool? unreadOnly,
    int? ageDays,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [],
          {
            #page: page,
            #limit: limit,
            #category: category,
            #unreadOnly: unreadOnly,
            #ageDays: ageDays,
          },
        ),
        returnValue:
            _i6.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #getMessages,
            [],
            {
              #page: page,
              #limit: limit,
              #category: category,
              #unreadOnly: unreadOnly,
              #ageDays: ageDays,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> searchMessages({
    required String? q,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMessages,
          [],
          {
            #q: q,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i6.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #searchMessages,
            [],
            {
              #q: q,
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> markMessageViewed(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMessageViewed,
          [id],
        ),
        returnValue:
            _i6.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #markMessageViewed,
            [id],
          ),
        )),
      ) as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> deleteMessage(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMessage,
          [id],
        ),
        returnValue:
            _i6.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteMessage,
            [id],
          ),
        )),
      ) as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getMessageStats({
    int? ageDays,
    bool? unreadOnly,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessageStats,
          [],
          {
            #ageDays: ageDays,
            #unreadOnly: unreadOnly,
          },
        ),
        returnValue:
            _i6.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #getMessageStats,
            [],
            {
              #ageDays: ageDays,
              #unreadOnly: unreadOnly,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getActivitySummary({
    bool? unreadOnly,
    bool? expiredOnly,
    int? ageDays,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivitySummary,
          [],
          {
            #unreadOnly: unreadOnly,
            #expiredOnly: expiredOnly,
            #ageDays: ageDays,
          },
        ),
        returnValue:
            _i6.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #getActivitySummary,
            [],
            {
              #unreadOnly: unreadOnly,
              #expiredOnly: expiredOnly,
              #ageDays: ageDays,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getUserUnifiedStats({
    bool? unreadOnly,
    bool? expiredOnly,
    int? ageDays,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserUnifiedStats,
          [],
          {
            #unreadOnly: unreadOnly,
            #expiredOnly: expiredOnly,
            #ageDays: ageDays,
          },
        ),
        returnValue:
            _i6.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #getUserUnifiedStats,
            [],
            {
              #unreadOnly: unreadOnly,
              #expiredOnly: expiredOnly,
              #ageDays: ageDays,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response<dynamic>>);
}
