// Mocks generated by Mockito 5.4.6 from annotations
// in stoyco_shared/test/stoycoins/stoycoins_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:stoyco_shared/envs/envs.dart' as _i4;
import 'package:stoyco_shared/stoycoins/models/donate.dart' as _i6;
import 'package:stoyco_shared/stoycoins/stoycoins_data_source.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StoycoinsDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoycoinsDataSource extends _i1.Mock
    implements _i3.StoycoinsDataSource {
  MockStoycoinsDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.StoycoEnvironment get environment => (super.noSuchMethod(
        Invocation.getter(#environment),
        returnValue: _i4.StoycoEnvironment.development,
      ) as _i4.StoycoEnvironment);

  @override
  _i5.Future<_i2.Response<dynamic>> getBalance({required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBalance,
          [],
          {#userId: userId},
        ),
        returnValue:
            _i5.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #getBalance,
            [],
            {#userId: userId},
          ),
        )),
      ) as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> donate(_i6.DonateModel? donateModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #donate,
          [donateModel],
        ),
        returnValue:
            _i5.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #donate,
            [donateModel],
          ),
        )),
      ) as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> getTransactionDetails({
    required String? userId,
    String? state,
    String? source,
    int? page,
    int? pageSize,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionDetails,
          [],
          {
            #userId: userId,
            #state: state,
            #source: source,
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue:
            _i5.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #getTransactionDetails,
            [],
            {
              #userId: userId,
              #state: state,
              #source: source,
              #page: page,
              #pageSize: pageSize,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response<dynamic>>);
}
