// Mocks generated by Mockito 5.4.6 from annotations
// in stoyco_shared/test/stoy_shop/stoy_shop_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i3;
import 'package:either_dart/either.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:stoyco_shared/cache/cache_manager.dart' as _i2;
import 'package:stoyco_shared/envs/envs.dart' as _i15;
import 'package:stoyco_shared/errors/error_handling/failure/failure.dart'
    as _i7;
import 'package:stoyco_shared/models/page_result/page_result.dart' as _i8;
import 'package:stoyco_shared/stoy_shop/models/minted_nft_model.dart' as _i13;
import 'package:stoyco_shared/stoy_shop/models/nft_metadata_model.dart' as _i12;
import 'package:stoyco_shared/stoy_shop/models/stoy_shop_category.dart' as _i10;
import 'package:stoyco_shared/stoy_shop/models/stoy_shop_product_model.dart'
    as _i9;
import 'package:stoyco_shared/stoy_shop/stoy_shop_data_source.dart' as _i14;
import 'package:stoyco_shared/stoy_shop/stoy_shop_repository.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCacheManager_0 extends _i1.SmartFake implements _i2.CacheManager {
  _FakeCacheManager_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_1<T> extends _i1.SmartFake implements _i3.Response<T> {
  _FakeResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StoyShopRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoyShopRepository extends _i1.Mock
    implements _i4.StoyShopRepository {
  MockStoyShopRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CacheManager get cacheManager => (super.noSuchMethod(
        Invocation.getter(#cacheManager),
        returnValue: _FakeCacheManager_0(
          this,
          Invocation.getter(#cacheManager),
        ),
      ) as _i2.CacheManager);

  @override
  set cacheManager(_i2.CacheManager? manager) => super.noSuchMethod(
        Invocation.setter(
          #cacheManager,
          manager,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i6.Either<_i7.Failure, _i8.PageResult<_i9.StoyShopProductModel>>>
      getOptimizedProducts({
    int? page = 1,
    int? pageSize = 100,
    _i10.StoyShopCategory? category,
    String? coId,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getOptimizedProducts,
              [],
              {
                #page: page,
                #pageSize: pageSize,
                #category: category,
                #coId: coId,
              },
            ),
            returnValue: _i5.Future<
                    _i6.Either<_i7.Failure,
                        _i8.PageResult<_i9.StoyShopProductModel>>>.value(
                _i11.dummyValue<
                    _i6.Either<_i7.Failure,
                        _i8.PageResult<_i9.StoyShopProductModel>>>(
              this,
              Invocation.method(
                #getOptimizedProducts,
                [],
                {
                  #page: page,
                  #pageSize: pageSize,
                  #category: category,
                  #coId: coId,
                },
              ),
            )),
          ) as _i5.Future<
              _i6
              .Either<_i7.Failure, _i8.PageResult<_i9.StoyShopProductModel>>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, _i12.NftMetadataModel>> getNftMetadata(
          String? metadataUri) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNftMetadata,
          [metadataUri],
        ),
        returnValue:
            _i5.Future<_i6.Either<_i7.Failure, _i12.NftMetadataModel>>.value(
                _i11.dummyValue<_i6.Either<_i7.Failure, _i12.NftMetadataModel>>(
          this,
          Invocation.method(
            #getNftMetadata,
            [metadataUri],
          ),
        )),
      ) as _i5.Future<_i6.Either<_i7.Failure, _i12.NftMetadataModel>>);

  @override
  _i5.Future<
      _i6.Either<_i7.Failure, List<_i13.MintedNftModel>>> getMintedNftsByUser({
    required int? collectionId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMintedNftsByUser,
          [],
          {
            #collectionId: collectionId,
            #userId: userId,
          },
        ),
        returnValue: _i5
            .Future<_i6.Either<_i7.Failure, List<_i13.MintedNftModel>>>.value(
            _i11.dummyValue<_i6.Either<_i7.Failure, List<_i13.MintedNftModel>>>(
          this,
          Invocation.method(
            #getMintedNftsByUser,
            [],
            {
              #collectionId: collectionId,
              #userId: userId,
            },
          ),
        )),
      ) as _i5.Future<_i6.Either<_i7.Failure, List<_i13.MintedNftModel>>>);

  @override
  _i5.Future<_i6.Either<_i7.Failure, T>> cachedCall<T>({
    required String? key,
    required Duration? ttl,
    required _i5.Future<_i6.Either<_i7.Failure, T>> Function()? fetcher,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cachedCall,
          [],
          {
            #key: key,
            #ttl: ttl,
            #fetcher: fetcher,
            #forceRefresh: forceRefresh,
          },
        ),
        returnValue: _i5.Future<_i6.Either<_i7.Failure, T>>.value(
            _i11.dummyValue<_i6.Either<_i7.Failure, T>>(
          this,
          Invocation.method(
            #cachedCall,
            [],
            {
              #key: key,
              #ttl: ttl,
              #fetcher: fetcher,
              #forceRefresh: forceRefresh,
            },
          ),
        )),
      ) as _i5.Future<_i6.Either<_i7.Failure, T>>);

  @override
  bool invalidateCache(String? key) => (super.noSuchMethod(
        Invocation.method(
          #invalidateCache,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  void invalidateCacheMultiple(List<String>? keys) => super.noSuchMethod(
        Invocation.method(
          #invalidateCacheMultiple,
          [keys],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool invalidateCachePattern(String? pattern) => (super.noSuchMethod(
        Invocation.method(
          #invalidateCachePattern,
          [pattern],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearAllCache() => super.noSuchMethod(
        Invocation.method(
          #clearAllCache,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [StoyShopDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoyShopDataSource extends _i1.Mock
    implements _i14.StoyShopDataSource {
  MockStoyShopDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.StoycoEnvironment get environment => (super.noSuchMethod(
        Invocation.getter(#environment),
        returnValue: _i15.StoycoEnvironment.development,
      ) as _i15.StoycoEnvironment);

  @override
  String get userToken => (super.noSuchMethod(
        Invocation.getter(#userToken),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#userToken),
        ),
      ) as String);

  @override
  set userToken(String? value) => super.noSuchMethod(
        Invocation.setter(
          #userToken,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateUserToken(String? newUserToken) => super.noSuchMethod(
        Invocation.method(
          #updateUserToken,
          [newUserToken],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i3.Response<dynamic>> getOptimizedProducts({
    int? page = 1,
    int? pageSize = 100,
    _i10.StoyShopCategory? category,
    String? coId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOptimizedProducts,
          [],
          {
            #page: page,
            #pageSize: pageSize,
            #category: category,
            #coId: coId,
          },
        ),
        returnValue:
            _i5.Future<_i3.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #getOptimizedProducts,
            [],
            {
              #page: page,
              #pageSize: pageSize,
              #category: category,
              #coId: coId,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response<dynamic>>);

  @override
  _i5.Future<_i3.Response<dynamic>> getNftMetadata(String? metadataUri) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNftMetadata,
          [metadataUri],
        ),
        returnValue:
            _i5.Future<_i3.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #getNftMetadata,
            [metadataUri],
          ),
        )),
      ) as _i5.Future<_i3.Response<dynamic>>);

  @override
  _i5.Future<_i3.Response<dynamic>> getMintedNftsByUser({
    required int? collectionId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMintedNftsByUser,
          [],
          {
            #collectionId: collectionId,
            #userId: userId,
          },
        ),
        returnValue:
            _i5.Future<_i3.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #getMintedNftsByUser,
            [],
            {
              #collectionId: collectionId,
              #userId: userId,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response<dynamic>>);
}
