// Mocks generated by Mockito 5.4.6 from annotations
// in stoyco_shared/test/stoy_shop/stoy_shop_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:stoyco_shared/envs/envs.dart' as _i4;
import 'package:stoyco_shared/stoy_shop/models/stoy_shop_category.dart' as _i7;
import 'package:stoyco_shared/stoy_shop/stoy_shop_data_source.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StoyShopDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoyShopDataSource extends _i1.Mock
    implements _i3.StoyShopDataSource {
  MockStoyShopDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.StoycoEnvironment get environment => (super.noSuchMethod(
        Invocation.getter(#environment),
        returnValue: _i4.StoycoEnvironment.development,
      ) as _i4.StoycoEnvironment);

  @override
  String get userToken => (super.noSuchMethod(
        Invocation.getter(#userToken),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#userToken),
        ),
      ) as String);

  @override
  set userToken(String? value) => super.noSuchMethod(
        Invocation.setter(
          #userToken,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateUserToken(String? newUserToken) => super.noSuchMethod(
        Invocation.method(
          #updateUserToken,
          [newUserToken],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i2.Response<dynamic>> getOptimizedProducts({
    int? page = 1,
    int? pageSize = 100,
    _i7.StoyShopCategory? category,
    String? coId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOptimizedProducts,
          [],
          {
            #page: page,
            #pageSize: pageSize,
            #category: category,
            #coId: coId,
          },
        ),
        returnValue:
            _i6.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #getOptimizedProducts,
            [],
            {
              #page: page,
              #pageSize: pageSize,
              #category: category,
              #coId: coId,
            },
          ),
        )),
      ) as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getNftMetadata(String? metadataUri) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNftMetadata,
          [metadataUri],
        ),
        returnValue:
            _i6.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #getNftMetadata,
            [metadataUri],
          ),
        )),
      ) as _i6.Future<_i2.Response<dynamic>>);
}
